
CREATE TABLE NhaCungCap (
    MaNCC VARCHAR(20) PRIMARY KEY,
    TenNCC VARCHAR(100),
    SDT VARCHAR(20),
    DiaChi VARCHAR(200)
);

CREATE TABLE NhanVien (
    MaNV VARCHAR(20) PRIMARY KEY,
    TenNV VARCHAR(100),
    SDT VARCHAR(20),
    ChucVu VARCHAR(50)
);

CREATE TABLE KhachHang (
    MaKH VARCHAR(20) PRIMARY KEY,
    TenKH VARCHAR(100),
    SDT VARCHAR(20),
    DiaChi VARCHAR(200)
);

CREATE TABLE SanPham (
    MaSP VARCHAR(20) PRIMARY KEY,
    TenSP VARCHAR(100),
    DonviTinh VARCHAR(50),
    SoLuong INT,
    Dongiaban DECIMAL(18, 2),
    Dongianhap DECIMAL(18, 2),
    MaNCC VARCHAR(20),
    FOREIGN KEY (MaNCC) REFERENCES NhaCungCap(MaNCC)
);

CREATE TABLE HoaDon (
    MaHD VARCHAR(20) PRIMARY KEY,
    NgayLap DATETIME,
    MaKH VARCHAR(20),
    MaNV VARCHAR(20),
    TongTien DECIMAL(18, 2),
    FOREIGN KEY (MaKH) REFERENCES KhachHang(MaKH),
    FOREIGN KEY (MaNV) REFERENCES NhanVien(MaNV)
);

CREATE TABLE CT_HoaDon (
    MaHD VARCHAR(20),
    MaSP VARCHAR(20),
    SoLuong INT,
    DonGia DECIMAL(18, 2),
    PRIMARY KEY (MaHD, MaSP),
    FOREIGN KEY (MaHD) REFERENCES HoaDon(MaHD),
    FOREIGN KEY (MaSP) REFERENCES SanPham(MaSP)
);

CREATE TABLE PhieuNhap (
    MaPN VARCHAR(20) PRIMARY KEY,
    NgayNhap DATETIME,
    MaNV VARCHAR(20),
    MaNCC VARCHAR(20),
    FOREIGN KEY (MaNV) REFERENCES NhanVien(MaNV),
    FOREIGN KEY (MaNCC) REFERENCES NhaCungCap(MaNCC)
);

CREATE TABLE CT_PhieuNhap (
    MaPN VARCHAR(20),
    MaSP VARCHAR(20),
    SoLuong INT,
    DonGiaNhap DECIMAL(18, 2),
    PRIMARY KEY (MaPN, MaSP),
    FOREIGN KEY (MaPN) REFERENCES PhieuNhap(MaPN),
    FOREIGN KEY (MaSP) REFERENCES SanPham(MaSP)
);

CREATE TABLE TaiKhoan (
    TenDangNhap VARCHAR(50) PRIMARY KEY,
    MatKhau VARCHAR(100),
    MaNV VARCHAR(20),
    FOREIGN KEY (MaNV) REFERENCES NhanVien(MaNV)
);
